### PR TITLE
[SPEC-251] Add helmet for header security

### PR DESCRIPTION
**Pull request by peterjgrainger**
Use default settings for header security

### CODE REVIEW

**Review by jenessaman — APPROVED** [review]
Awesome!

**Comment by daviddekoning** [comment]
Peter can we use a whitelist approach as opposed to a black list? That is, enforce that the returned string strictly meets the definition of a URL rather than checking that is doesn't have certain bad things. This way we are still covered if new types of "bad" elements get added to the HTML spec down the line...

**Comment by peterjgrainger** [comment]
@daviddekoning something like this? :point_down: 

image

**Comment by daviddekoning** [comment]
Beauty, eh!

**Comment by daviddekoning** [comment]
p.s. I'll be setting up a general help desk email address, so we can switch to that when it's live. 

Are we logging the failed callback URL?

**Comment by peterjgrainger** [comment]
> p.s. I'll be setting up a general help desk email address, so we can switch to that when it's live.
> 
> Are we logging the failed callback URL?

no we aren't. Good idea, I'll add that

**Pull request merged**
